// Ferry Timetable Data - Now generated by the route generator system
// The ferrySchedule variable is populated by sfk-f2-route.js

// Global variable to track selected station
let selectedStation = null;

// Utility functions
function timeToMinutes(time) {
    const hours = Math.floor(time);
    const minutes = Math.round((time - hours) * 100);
    return hours * 60 + minutes;
}

function minutesToTime(minutes) {
    const hours = Math.floor(minutes / 60);
    const mins = minutes % 60;
    return `${hours.toString().padStart(2, '0')}:${mins.toString().padStart(2, '0')}`;
}

function getCurrentDaySchedule() {
    const now = new Date();
    const dayOfWeek = now.getDay(); // 0 = Sunday, 1 = Monday, ..., 6 = Saturday
    
    if (dayOfWeek === 0) {
        return null; // No service on Sunday
    } else if (dayOfWeek === 6) {
        return window.ferrySchedule ? window.ferrySchedule.saturday : null;
    } else {
        return window.ferrySchedule ? window.ferrySchedule.weekdays : null;
    }
}

function findNextTime(times, currentMinutes) {
    // Find the next time today
    for (let time of times) {
        const timeMinutes = timeToMinutes(time);
        if (timeMinutes > currentMinutes) {
            return timeMinutes;
        }
    }
    
    // If no more times today, return the first time tomorrow
    return timeToMinutes(times[0]);
}

function calculateCountdown(nextTimeMinutes, currentMinutes) {
    let diff = nextTimeMinutes - currentMinutes;
    
    if (diff < 0) {
        // Next time is tomorrow
        diff += 24 * 60;
    }
    
    if (diff < 60) {
        return `in ${diff}min`;
    } else {
        const hours = Math.floor(diff / 60);
        const minutes = diff % 60;
        if (minutes === 0) {
            return `in ${hours}h`;
        } else {
            return `in ${hours}h ${minutes}min`;
        }
    }
}

function updateCurrentTime() {
    const now = new Date();
    const timeString = now.toLocaleTimeString('de-DE', {
        hour: '2-digit',
        minute: '2-digit',
        hour12: false
    });
    document.getElementById('current-time').textContent = timeString;
    return now;
}

function updateStationTimes(station, schedule) {
    if (!schedule) {
        // No service today
        document.getElementById(`${station}-arrival`).textContent = 'Kein Betrieb';
        return;
    }
    
    const now = new Date();
    const currentMinutes = now.getHours() * 60 + now.getMinutes();
    
    // For all stations, show departure time countdown
    const nextTime = findNextTime(schedule[station].departures, currentMinutes);
    const countdownText = calculateCountdown(nextTime, currentMinutes);
    
    // Update arrival display (keeping the ID for consistency)
    const arrivalElement = document.getElementById(`${station}-arrival`);
    
    if (arrivalElement.textContent !== countdownText) {
        arrivalElement.textContent = countdownText;
        arrivalElement.classList.add('updated');
        setTimeout(() => arrivalElement.classList.remove('updated'), 500);
    }
}

function updateDepartureTimesForStation(station, schedule) {
    if (!schedule) {
        // No service today
        const departureElements = [
            document.getElementById(`${station}-departure-1`),
            document.getElementById(`${station}-departure-2`),
            document.getElementById(`${station}-departure-3`)
        ];
        
        departureElements.forEach((element, index) => {
            if (element) {
                element.textContent = index === 0 ? 'Kein Betrieb' : '';
            }
        });
        return;
    }
    
    const now = new Date();
    const currentMinutes = now.getHours() * 60 + now.getMinutes();
    
    // Get departure times for the station
    const departureTimes = schedule[station].departures;
    let nextDepartures = [];
    
    for (let time of departureTimes) {
        const timeMinutes = timeToMinutes(time);
        if (timeMinutes > currentMinutes) {
            nextDepartures.push(timeMinutes);
            if (nextDepartures.length >= 3) break;
        }
    }
    
    // If we don't have 3 departures today, add from tomorrow
    if (nextDepartures.length < 3) {
        for (let time of departureTimes) {
            const timeMinutes = timeToMinutes(time);
            nextDepartures.push(timeMinutes);
            if (nextDepartures.length >= 3) break;
        }
    }
    
    // Update departure time displays
    const departureElements = [
        document.getElementById(`${station}-departure-1`),
        document.getElementById(`${station}-departure-2`),
        document.getElementById(`${station}-departure-3`)
    ];
    
    nextDepartures.slice(0, 3).forEach((time, index) => {
        if (departureElements[index]) {
            departureElements[index].textContent = minutesToTime(time);
        }
    });
}

function updateAllStations() {
    const schedule = getCurrentDaySchedule();
    
    // Get all station IDs from the generated HTML
    const stationItems = document.querySelectorAll('.station-item');
    stationItems.forEach(stationItem => {
        const stationId = stationItem.id;
        updateStationTimes(stationId, schedule);
    });
    
    // Update departure times for selected station if any
    if (selectedStation) {
        updateDepartureTimesForStation(selectedStation, schedule);
    }
}

function selectStation(station) {
    // Hide all departure time sections
    document.querySelectorAll('.departure-times-station').forEach(section => {
        section.style.display = 'none';
    });
    
    // Remove active state from all stations
    document.querySelectorAll('.station-item').forEach(item => {
        item.classList.remove('active');
    });
    
    // If clicking the same station, deselect it
    if (selectedStation === station) {
        selectedStation = null;
        return;
    }
    
    // Add active state to selected station
    document.getElementById(station).classList.add('active');
    
    // Show departure times for selected station
    const departureSection = document.getElementById(`${station}-departures`);
    if (departureSection) {
        departureSection.style.display = 'block';
    }
    
    // Update selected station
    selectedStation = station;
    
    // Update the departure times display
    const schedule = getCurrentDaySchedule();
    updateDepartureTimesForStation(station, schedule);
}

function initializeApp() {
    // Wait for the route to be generated before initializing
    if (!window.ferrySchedule) {
        // If ferry schedule isn't ready yet, wait a bit and try again
        setTimeout(initializeApp, 100);
        return;
    }
    
    // Update times immediately
    updateCurrentTime();
    updateAllStations();
    
    // Update every minute
    setInterval(() => {
        updateCurrentTime();
        updateAllStations();
    }, 60000);
    
    // Update current time every second for smooth display
    setInterval(updateCurrentTime, 1000);
}

// Initialize the app when the page loads
document.addEventListener('DOMContentLoaded', function() {
    // Wait a bit for the route generation to complete
    setTimeout(initializeApp, 200);
});

// Add some interactive features
document.addEventListener('DOMContentLoaded', function() {
    // Wait for stations to be generated before adding event listeners
    setTimeout(() => {
        // Add click effects to station items
        const stationItems = document.querySelectorAll('.station-item');
        stationItems.forEach(item => {
            item.addEventListener('click', function() {
                // Get the station ID from the element
                const stationId = this.id;
                
                // Select the station
                selectStation(stationId);
                
                // Add click animation
                this.style.transform = 'scale(0.98)';
                setTimeout(() => {
                    this.style.transform = '';
                }, 150);
            });
        });
        
        // Add hover effects for better UX
        stationItems.forEach(item => {
            item.addEventListener('mouseenter', function() {
                if (!this.classList.contains('active')) {
                    this.style.transform = 'translateY(-2px)';
                }
            });
            
            item.addEventListener('mouseleave', function() {
                if (!this.classList.contains('active')) {
                    this.style.transform = '';
                }
            });
        });
    }, 300);
});
