// Ferry Timetable Data - Now generated by the route generator system
// The ferrySchedule variable is populated by sfk-f2-route.js

// Global variable to track selected station
let selectedStation = null;

// Utility functions
function timeToMinutes(time) {
    const hours = Math.floor(time);
    const minutes = Math.round((time - hours) * 100);
    return hours * 60 + minutes;
}

function minutesToTime(minutes) {
    const hours = Math.floor(minutes / 60);
    const mins = minutes % 60;
    return `${hours.toString().padStart(2, '0')}:${mins.toString().padStart(2, '0')}`;
}

const publicHolidayCache = new Map();
let holidayFetchStarted = false;

function buildHolidayKey(date) {
    return date.toISOString().slice(0, 10);
}

function isPublicHoliday(date) {
    const key = buildHolidayKey(date);
    return publicHolidayCache.has(key);
}

function getHolidayName(date) {
    const key = buildHolidayKey(date);
    return publicHolidayCache.get(key) || '';
}

async function fetchSchleswigHolsteinHolidays(year) {
    const url = `https://date.nager.at/api/v3/PublicHolidays/${year}/DE`;
    const response = await fetch(url);

    if (!response.ok) {
        throw new Error(`Holiday API request failed for ${year}: ${response.status}`);
    }

    const holidays = await response.json();
    holidays.forEach(holiday => {
        const counties = holiday.counties || [];
        if (!counties.length || counties.includes('DE-SH')) {
            publicHolidayCache.set(holiday.date, holiday.localName || holiday.name);
        }
    });
}

async function loadSchleswigHolsteinHolidays(startYear, endYear) {
    if (holidayFetchStarted) return;
    holidayFetchStarted = true;

    const fetchPromises = [];
    for (let year = startYear; year <= endYear; year += 1) {
        fetchPromises.push(fetchSchleswigHolsteinHolidays(year));
    }

    await Promise.all(fetchPromises);
    updateAllStations();
}

function isInOperation(date) {
    if (!window.ferrySchedule || !window.ferrySchedule.InOperation) return false;

    const dayOfWeek = date.getDay();
    if (dayOfWeek === 0) {
        return window.ferrySchedule.InOperation.sunday;
    }
    if (dayOfWeek === 6) {
        return window.ferrySchedule.InOperation.saturday;
    }
    if (isPublicHoliday(date)) {
        return window.ferrySchedule.InOperation.publicHolidays;
    }
    return window.ferrySchedule.InOperation.weekday;
}

function getScheduleForDate(date) {
    if (!window.ferrySchedule || !isInOperation(date)) {
        return null;
    }

    const dayOfWeek = date.getDay();
    const schedule = {};
    const isHoliday = isPublicHoliday(date);

    if (isHoliday || dayOfWeek === 0) {
        // Sunday or public holiday schedule
        Object.keys(window.ferrySchedule).forEach(stationId => {
            const station = window.ferrySchedule[stationId];
            if (station.sundayDepartures) {
                schedule[stationId] = {
                    departures: station.sundayDepartures,
                    arrivals: station.sundayArrivals || station.sundayDepartures,
                    name: station.name
                };
            } else if (station.saturdayDepartures) {
                schedule[stationId] = {
                    departures: station.saturdayDepartures,
                    arrivals: station.saturdayArrivals || station.saturdayDepartures,
                    name: station.name
                };
            }
        });
        return schedule;
    } else if (dayOfWeek === 6) {
        // Saturday
        Object.keys(window.ferrySchedule).forEach(stationId => {
            const station = window.ferrySchedule[stationId];
            if (station.saturdayDepartures) {
                schedule[stationId] = {
                    departures: station.saturdayDepartures,
                    arrivals: station.saturdayArrivals || station.saturdayDepartures,
                    name: station.name
                };
            }
        });
        return schedule;
    } else {
        // Weekdays
        Object.keys(window.ferrySchedule).forEach(stationId => {
            const station = window.ferrySchedule[stationId];
            schedule[stationId] = {
                departures: station.departures,
                arrivals: station.arrivals || station.departures,
                name: station.name
            };
        });
        return schedule;
    }
}

function getCurrentDaySchedule() {
    return getScheduleForDate(new Date());
}

function findNextTime(times, currentMinutes, nextDayTimes) {
    // Find the next time today
    for (let time of times) {
        const timeMinutes = timeToMinutes(time);
        if (timeMinutes > currentMinutes) {
            return timeMinutes;
        }
    }

    // No more times today: use tomorrow's actual schedule (day-type may differ, e.g. weekday -> weekend)
    const fallbackTimes = nextDayTimes && nextDayTimes.length ? nextDayTimes : times;
    return timeToMinutes(fallbackTimes[0]);
}

function calculateCountdown(nextTimeMinutes, currentMinutes) {
    let diff = nextTimeMinutes - currentMinutes;

    if (diff < 0) {
        // Next time is tomorrow
        diff += 24 * 60;
    }

    if (diff < 60) {
        return `in ${diff}min`;
    } else {
        const hours = Math.floor(diff / 60);
        const minutes = diff % 60;
        if (minutes === 0) {
            return `in ${hours}h`;
        } else {
            return `in ${hours}h ${minutes}min`;
        }
    }
}

function updateCurrentTime() {
    const now = new Date();
    const timeString = now.toLocaleTimeString('de-DE', {
        hour: '2-digit',
        minute: '2-digit',
        hour12: false
    });
    document.getElementById('current-time').textContent = timeString;
    renderHolidayStatus(now);
    return now;
}

function renderHolidayStatus(date) {
    const holidayName = getHolidayName(date);
    let indicator = document.getElementById('holiday-indicator');
    let scheduleIndicator = document.getElementById('holiday-schedule-indicator');
    const timeDisplay = document.querySelector('.time-display');
    const scheduleInfo = document.querySelector('.schedule-info');

    if (!timeDisplay || !scheduleInfo) return;

    if (!indicator) {
        indicator = document.createElement('span');
        indicator.id = 'holiday-indicator';
        indicator.className = 'holiday-message';
        timeDisplay.appendChild(indicator);
    }

    if (!scheduleIndicator) {
        scheduleIndicator = document.createElement('div');
        scheduleIndicator.id = 'holiday-schedule-indicator';
        scheduleIndicator.className = 'holiday-banner';
        scheduleInfo.insertBefore(scheduleIndicator, scheduleInfo.firstChild);
    }

    if (holidayName) {
        const labelText = `Feiertag: ${holidayName}`;
        indicator.textContent = labelText;
        indicator.style.display = 'block';
        scheduleIndicator.textContent = `${labelText} - Fahrplan gilt für Sonntag/Feiertag.`;
        scheduleIndicator.style.display = 'block';
    } else {
        indicator.textContent = '';
        indicator.style.display = 'none';
        scheduleIndicator.textContent = '';
        scheduleIndicator.style.display = 'none';
    }
}

function updateStationTimes(station, schedule) {
    if (!schedule) {
        // No service today
        document.getElementById(`${station}-arrival`).textContent = 'Kein Betrieb';
        return;
    }

    const now = new Date();
    const currentMinutes = now.getHours() * 60 + now.getMinutes();

    const tomorrow = new Date(now);
    tomorrow.setDate(now.getDate() + 1);
    const tomorrowSchedule = getScheduleForDate(tomorrow);
    const tomorrowTimes = tomorrowSchedule?.[station]?.departures || [];

    // For all stations, show departure time countdown
    const nextTime = findNextTime(schedule[station].departures, currentMinutes, tomorrowTimes);
    const countdownText = calculateCountdown(nextTime, currentMinutes);

    // Update arrival display (keeping the ID for consistency)
    const arrivalElement = document.getElementById(`${station}-arrival`);

    if (arrivalElement.textContent !== countdownText) {
        arrivalElement.textContent = countdownText;
        arrivalElement.classList.add('updated');
        setTimeout(() => arrivalElement.classList.remove('updated'), 500);
    }
}

function updateDepartureTimesForStation(station, schedule) {
    const allDeparturesElement = document.getElementById(`${station}-all-departures`);
    if (!schedule) {
        if (allDeparturesElement) {
            allDeparturesElement.innerHTML = '<div class="departure-time-item">Kein Betrieb heute</div>';
        }
        return;
    }

    const now = new Date();
    const currentMinutes = now.getHours() * 60 + now.getMinutes();
    const upcomingDepartures = [];

    const todayTimes = schedule[station]?.departures || [];
    todayTimes.forEach(time => {
        const timeMinutes = timeToMinutes(time);
        if (timeMinutes > currentMinutes) {
            upcomingDepartures.push({ minutes: timeMinutes, isTomorrow: false });
        }
    });

    const tomorrow = new Date(now);
    tomorrow.setDate(now.getDate() + 1);
    const tomorrowSchedule = getScheduleForDate(tomorrow);
    const tomorrowTimes = tomorrowSchedule?.[station]?.departures || [];

    tomorrowTimes.forEach(time => {
        upcomingDepartures.push({ minutes: timeToMinutes(time), isTomorrow: true });
    });

    if (upcomingDepartures.length === 0 && allDeparturesElement) {
        allDeparturesElement.innerHTML = '<div class="departure-time-item">Keine weiteren Abfahrten heute oder morgen</div>';
        return;
    }

    updateAllDeparturesList(station, upcomingDepartures, currentMinutes);
}

function updateAllDeparturesList(station, upcomingDepartures, currentMinutes) {
    const allDeparturesElement = document.getElementById(`${station}-all-departures`);
    if (!allDeparturesElement) return;

    if (upcomingDepartures.length === 0) {
        allDeparturesElement.innerHTML = '<div class="departure-time-item">Keine weiteren Abfahrten heute</div>';
        return;
    }

    let departuresHTML = '';

    upcomingDepartures.forEach((departureItem) => {
        const departureTime = typeof departureItem === 'object' ? departureItem.minutes : departureItem;
        const isTomorrow = typeof departureItem === 'object' ? departureItem.isTomorrow : departureTime < currentMinutes;
        const countdown = calculateCountdown(departureTime, currentMinutes);
        const timeString = minutesToTime(departureTime);
        const itemClass = isTomorrow ? 'departure-time-item tomorrow' : 'departure-time-item';

        departuresHTML += `
            <div class="${itemClass}">
                <span class="time">${timeString}</span>
                <span class="countdown">${countdown}${isTomorrow ? ' (morgen)' : ''}</span>
            </div>
        `;
    });

    allDeparturesElement.innerHTML = departuresHTML;
}

function updateAllStations() {
    const schedule = getCurrentDaySchedule();

    // Get all station IDs from the generated HTML
    const stationItems = document.querySelectorAll('.station-item');
    stationItems.forEach(stationItem => {
        const stationId = stationItem.id;
        updateStationTimes(stationId, schedule);
    });

    // Update departure times for selected station if any
    if (selectedStation) {
        updateDepartureTimesForStation(selectedStation, schedule);
    }
}

function selectStation(station) {
    // Hide all departure time sections
    document.querySelectorAll('.departure-times-station').forEach(section => {
        section.style.display = 'none';
    });

    // Remove active state from all stations
    document.querySelectorAll('.station-item').forEach(item => {
        item.classList.remove('active');
    });

    // If clicking the same station, deselect it
    if (selectedStation === station) {
        selectedStation = null;
        return;
    }

    // Add active state to selected station
    document.getElementById(station).classList.add('active');

    // Show departure times for selected station
    const departureSection = document.getElementById(`${station}-departures`);
    if (departureSection) {
        departureSection.style.display = 'block';
    }

    // Update selected station
    selectedStation = station;

    // Update the departure times display
    const schedule = getCurrentDaySchedule();
    updateDepartureTimesForStation(station, schedule);
}

function initializeApp() {
    // Wait for the route to be generated before initializing
    if (!window.ferrySchedule) {
        // If ferry schedule isn't ready yet, wait a bit and try again
        setTimeout(initializeApp, 100);
        return;
    }
    console.log("called initializeApp");

    const now = new Date();
    loadSchleswigHolsteinHolidays(now.getFullYear() - 1, now.getFullYear() + 2);

    // Update times immediately
    updateCurrentTime();
    updateAllStations();

    // Update every minute
    setInterval(() => {
        updateCurrentTime();
        updateAllStations();
    }, 60000);

    // Update current time every second for smooth display
    setInterval(updateCurrentTime, 1000);
}

// Function to initialize main script functionality (called when routes are switched)
function initializeMainScript() {
    // Re-add click event listeners to stations
    const stations = document.querySelectorAll('.station-item');
    stations.forEach(station => {
        station.addEventListener('click', function () {
            const stationId = this.id;
            const schedule = window.ferrySchedule;

            // Hide all departure sections first
            document.querySelectorAll('.departure-times-station').forEach(section => {
                section.style.display = 'none';
            });

            // Remove active class from all stations
            document.querySelectorAll('.station-item').forEach(s => {
                s.classList.remove('active');
            });

            // Add active class to clicked station
            this.classList.add('active');

            // Show departure times for this station
            const departureSection = document.getElementById(`${stationId}-departures`);
            if (departureSection) {
                departureSection.style.display = 'block';
                const currentSchedule = getCurrentDaySchedule();
                updateDepartureTimesForStation(stationId, currentSchedule);
            }
        });
    });
}

// Initialize when page loads
document.addEventListener('DOMContentLoaded', function () {
    // Initial setup will be handled by routes manager
    // This function will be called when routes are switched
});

// Add some interactive features
document.addEventListener('DOMContentLoaded', function () {
    // Wait for stations to be generated before adding event listeners
    setTimeout(() => {
        // Add click effects to station items
        const stationItems = document.querySelectorAll('.station-item');
        stationItems.forEach(item => {
            item.addEventListener('click', function () {
                // Get the station ID from the element
                const stationId = this.id;

                // Select the station
                console.log("selectStation Event")
                selectStation(stationId);

                // Add click animation
                this.style.transform = 'scale(0.98)';
                setTimeout(() => {
                    this.style.transform = '';
                }, 150);
            });
        });

        // Add hover effects for better UX
        stationItems.forEach(item => {
            item.addEventListener('mouseenter', function () {
                if (!this.classList.contains('active')) {
                    this.style.transform = 'translateY(-2px)';
                }
            });

            item.addEventListener('mouseleave', function () {
                if (!this.classList.contains('active')) {
                    this.style.transform = '';
                }
            });
        });
    }, 300);
});
